[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xb820eecaec3cf7d876247bd267634c1d0bf2c326e667e58aa2fbc3275abd8f3c'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]